[package]
name = "rust_github_testing"
version = "0.1.0"
authors = ["David Sweeney <sweeney@tamu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
